/*
 * This code was generated by ojc.
 */
import GeneticAlgorithm.InstrumentCode.*;


public class DateUtil
{

    public DateUtil()
    {
        trace.add( new java.lang.Integer( 1 ) );
    }

    public int daysInMonth( MyDate date )
    {
        trace.add( new java.lang.Integer( 2 ) );
        if (date.getMonth() <= 0 || date.getMonth() > 12) {
            trace.add( new java.lang.Integer( 3 ) );
            return -1;
        } else {
            trace.add( new java.lang.Integer( 4 ) );
        }
        if (date.getMonth() == 2) {
            trace.add( new java.lang.Integer( 5 ) );
            if (date.isLeapYear()) {
                trace.add( new java.lang.Integer( 6 ) );
                return 29;
            } else {
                trace.add( new java.lang.Integer( 7 ) );
                return 28;
            }
        } else {
            trace.add( new java.lang.Integer( 8 ) );
        }
        if (date.getMonth() <= 7) {
            trace.add( new java.lang.Integer( 9 ) );
            if (date.getMonth() % 2 == 1) {
                trace.add( new java.lang.Integer( 10 ) );
                return 31;
            } else {
                trace.add( new java.lang.Integer( 11 ) );
                return 30;
            }
        } else {
            trace.add( new java.lang.Integer( 12 ) );
        }
        if (date.getMonth() % 2 == 0) {
            trace.add( new java.lang.Integer( 13 ) );
            return 31;
        } else {
            trace.add( new java.lang.Integer( 14 ) );
            return 30;
        }
    }

    
    static java.util.Set trace = new java.util.HashSet();

    
    public static void newTrace()
    {
        trace = new java.util.HashSet();
    }

    
    public static java.util.Set getTrace()
    {
        return trace;
    }

}
