
/*
 * This code was generated by ojc.
 */
import GeneticAlgorithm.InstrumentCode.*;


public class Triangle1
{

    int side1;

    int side2;

    int side3;

    public Triangle1()
    {
        trace.add( new java.lang.Integer( 9 ) );
    }

    public Triangle1( int side1, int side2, int side3 )
    {
        super();
        trace.add( new java.lang.Integer( 10 ) );
        this.side1 = side1;
        this.side2 = side2;
        this.side3 = side3;
    }

    public Triangle1( int side1, int side2 )
    {
        super();
        trace.add( new java.lang.Integer( 11 ) );
        this.side1 = side1;
        this.side2 = side2;
        this.side3 = side2;
    }

    public Triangle1( int side1 )
    {
        super();
        trace.add( new java.lang.Integer( 12 ) );
        this.side1 = side1;
        this.side2 = side1;
        this.side3 = side1;
    }

    
    static java.util.Set trace = new java.util.HashSet();

    
    public static void newTrace()
    {
        trace = new java.util.HashSet();
    }

    
    public static java.util.Set getTrace()
    {
        return trace;
    }

}
